### ISSUE TITLE
i need ffmpeg6.1 for win on arm64

### ISSUE THREAD

**Issue by wmx-github** [dvhh/ffmpeg-wos-arm64-build#10]
i need ffmpeg6.1 for win on arm64,can you help me ,thanks

**Comment by dvhh** [comment]
getting a look at it

**Comment by dvhh** [comment]
Hello @wmx-github ,

kindly find the build [here](https://github.com/dvhh/ffmpeg-wos-arm64-build/releases/tag/release-6.1)

**Comment by dvhh** [comment]
Just in case, feel free to fork and keep the specific branch, I don't know how long I will keep them alive
