### ISSUE TITLE
More encoders, libx265

### ISSUE THREAD

**Issue by DaedlyKitten** [dvhh/ffmpeg-wos-arm64-build#11]
Hi Great work, really appreciate the build,, 

could you include more encoders like libx265?

**Comment by dvhh** [comment]
Hello @DaedlyKitten, thanks for sumbitting the request, will get a look at it this week

**Comment by dvhh** [comment]
Hello @DaedlyKitten,
Would you kindly test the following archive [ffmpeg-wos-arm64.zip](https://github.com/dvhh/ffmpeg-wos-arm64-build/releases/download/x265/) and confirm ?

**Comment by DaedlyKitten** [comment]
Hi Dvhh, libx265 working flawlessly !! 
Thank you! 👍 

I also tried comparing to WSL2 arm64 linux build of ffmpeg from default apt install, and it seems to have twice the performance (I got 2 times the encoding speed on my test files)
:D

**Comment by dvhh** [comment]
If you have some time, I have started some pipeline refactoring to add more codecs 
would you kindly try this build [ffmpeg-mingw32-arm64.zip](https://github.com/dvhh/ffmpeg-wos-arm64-build/releases/download/14-split-build-files/ffmpeg-mingw32-arm64.zip)
