### ISSUE TITLE
How to add support for libx264

### ISSUE THREAD

**Issue by MtnViewJohn** [dvhh/ffmpeg-wos-arm64-build#4]
I'm developing a C# Winforms application that uses ffmpeg for H.264 video encoding. I'm trying out your DLLs to get this to work on arm64. But it doesn't work because your build only has the h264_mf codec, not the libx264 codec that I was successfully using on x86_64 systems. I can't use the h264_mf codec because it requires that my application use the MTA threading model and I have to use the STA threading model. Libx264 does not care about threading models.

So I was wondering if you could either enable libx264 in your build or give me some tips on how to enable libx264 in my own fork.

**Comment by dvhh** [comment]
Hello @MtnViewJohn,

will look at the issue

**Comment by dvhh** [comment]
Hello @MtnViewJohn,

Could you test with https://github.com/dvhh/ffmpeg-wos-arm64-build/releases/download/libx264/ffmpeg-wos-arm64.zip ?

**Comment by MtnViewJohn** [comment]
That works perfectly. Thanks.

**Comment by dvhh** [comment]
Merged
